### PR TITLE
Adding my article Write Better + Some improvements in README.md

### PR DESCRIPTION
**Pull request by jmfayard**
Hello,

I've discovered Markdown since two months or so, and it's such a pity
that it's not more well-known.

But that's not terribly strange either. It's hard to find the right
information about it. Even the wikipedia article needs a lot of
rewritings.

So first I wrote an article about why we must kill the idea that you
need Microsoft Word to write words. And why things like BBcode must die.

Then I wanted to launch a website with even more information.

Finally, I thought that maybe someone had the same idea.

And here I am :-)

PS: you may have guessed that english is not that my native tongue, and that it needs proof-reading ;-)

### CODE REVIEW

**Comment by kirkstrobeck** [comment]
thx! i'll look into it

**Comment by kirkstrobeck** [comment]
Where were you thinking `write-better.txt` would appear?

**Comment by jmfayard** [comment]
Hello Kirk !

Thanks for thinking that my contribution is useful.

Your question is important. 
Putting all the content about markdown in the main page of the site was fine to begin with.

I thought that we should now divide it in, by displaying at the top links to the main parts we already have 

(Markdown for Human beings) (Markdown for Developers) (The future of markdown) (Write Better)

Markdown for Human beings would be here the default page.
Since, hey, we do that for human beings first, and the developers will be more interested in markdown only when their users will be able to use it anyway. 
The future of markdown is another important part, but I saw that we don't agree on that topic : your opinion seems to be that markdown must be improved, I think that it must keep simple. We can write an article about our two opinions and see how we can agree on that (I think we will agree that there must be someday an official markdown 2.0 syntax).
But for now, my point is that we should put that in a separate article.

---

Now I want to add something even more important, at least to me.

I didn't tell it the first time I contacted you, but if think that markdown has a great potential.
If you created this website in the first place, I think that you will agree with me.

Well now, what will perhaps look strange for you is that I would like that we think how we can make the website 
ready for being translated in different languages right now.

I, for sure, will translate the main page and my article in french.

Why may it look strange for you ?

Because most people, especially if english is their mother tongue, think that most people "speak enlgish" anyway,
so it's not really needed.

I don't want you to get me wrong. I have learned to love english, it's a wonderful, very useful language.
But I had myself too much difficulties to learn it (and I still don't really master it), and I've travelled too much,
discussed too much with many people from very different cultures, who themselves too have important language handicaps.
I know for a fact that, while it may sound sad, it is just wrong right now that most people really master english.

What's more, even if this wasn't true, this famous remark from Nelson Mandela would still hold :

nelson mandela quote 2013-08-16_11-10-37

Ok, so right now, what I need is that you create an "fr" folder and I will put there my own translations of my article, then the rest

Then we will have to think about the UX (you seem to know a lot about this)

This is not easy to get a multilingual website right, but fortunately, there are good guidelines avaible 
- http://www.howto.gov/web-content/multilingual/best-practices
- https://support.google.com/webmasters/answer/182192?hl=en

I hope to hear from you :)

**Comment by jmfayard** [comment]
Hello again Kirk,

what do you think of the idea of replacing the big unofficial markdown logo on the homepage with 

<a href="https://github.com/kirkstrobeck/whatismarkdown"></a>

(click on it to see where it goes)

**Comment by kirkstrobeck** [comment]
If you'd like to simplify some of your edits I'd be happy to consider them in a new pull request. 

It looks like you've got some great ideas for a site of your own, but I'm not sure whatismarkdown will be much more than a simple instructional/inspirational page. Thanks for the contributions tho! If you want to see the types of changes I'd accept, see https://github.com/kirkstrobeck/whatismarkdown/pulls?direction=desc&page=1&sort=created&state=closed

**Pull request closed without merging**
